# Generated by Django 6.0.8 on 2026-09-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_firebase_provider_user_firebase_uid"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="registration_completed",
            field=models.BooleanField(default=False),
        ),
    ]
